# Generated by Django 5.0.7 on 2024-07-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aftomabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, max_length=100, null=True)),
                ('raqami', models.CharField(blank=True, max_length=20, null=True)),
                ('summa', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aftomabil',
            },
        ),
        migrations.CreateModel(
            name='Istemolchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('pazivnoy', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('aftomabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aftomabil')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'istemolchi',
            },
        ),
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('sana', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('istemolchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.istemolchi')),
            ],
            options={
                'db_table': 'qarz',
            },
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naxt', models.PositiveIntegerField(blank=True, null=True)),
                ('karta', models.PositiveIntegerField(blank=True, null=True)),
                ('izox', models.TextField(blank=True, null=True)),
                ('sana', models.DateField()),
                ('sana2', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('istemolchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.istemolchi')),
            ],
            options={
                'db_table': 'tolov',
            },
        ),
    ]
