# Generated by Django 5.0.7 on 2024-07-18 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarz',
            old_name='sana',
            new_name='date_creat',
        ),
        migrations.RenameField(
            model_name='tolov',
            old_name='sana',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tolov',
            old_name='sana2',
            new_name='date_edit',
        ),
        migrations.AddField(
            model_name='qarz',
            name='date_edit',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tolov',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
