# Generated by Django 5.0.7 on 2024-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sana_qarz_date_creat_rename_sana_tolov_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftomabil',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
