# Generated by Django 5.0.7 on 2024-07-20 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aftomabil_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='qarz',
            old_name='date_edit',
            new_name='date_delete',
        ),
        migrations.AddField(
            model_name='istemolchi',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('oylik', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xodim',
            },
        ),
        migrations.CreateModel(
            name='Maosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('izox', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xodim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.xodim')),
            ],
            options={
                'db_table': 'maosh',
            },
        ),
    ]
