# Generated by Django 5.0.7 on 2024-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_date_edit_qarz_date_delete_istemolchi_aktiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
