# Generated by Django 5.0.7 on 2024-07-21 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aftomabil_author_alter_istemolchi_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('izox', models.TextField(blank=True, null=True)),
                ('Aftomabil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.aftomabil')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_cost',
            },
        ),
    ]
