# Generated by Django 5.0.7 on 2024-07-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_cost',
            old_name='Aftomabil',
            new_name='aftomabil',
        ),
    ]
