# Generated by Django 5.0.7 on 2024-07-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_aftomabil_car_cost_aftomabil'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_cost',
            name='date',
            field=models.DateField(default='2024-06-10'),
            preserve_default=False,
        ),
    ]
