# Generated by Django 5.0.7 on 2024-07-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_car_cost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_cost',
            name='date_creat',
            field=models.DateField(auto_now_add=True, default='2024-07-20'),
            preserve_default=False,
        ),
    ]
